@echo off
chcp 65001 >nul
:: Image-Viewer Windows Installer
:: Universal installer for Windows 7/8/10/11 - no admin rights needed

setlocal EnableDelayedExpansion

echo =========================================
echo Image-Viewer Windows Installation
echo =========================================
echo.

:: Detect Windows version
for /f "tokens=4-5 delims=. " %%i in ('ver') do set WIN_VER=%%i

:: Get script directory
set "SCRIPT_DIR=%~dp0"
set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"

:: Try to find image-viewer.exe in various locations
set "EXE_FOUND=0"
set "EXE_PATH="

:: Check 1: Same directory as script
if exist "%SCRIPT_DIR%\image-viewer.exe" (
    set "EXE_PATH=%SCRIPT_DIR%\image-viewer.exe"
    set "EXE_FOUND=1"
    goto :found_exe
)

:: Check 2: Parent directory (for install/windows/ structure)
if exist "%SCRIPT_DIR%\..\..\image-viewer.exe" (
    for %%F in ("%SCRIPT_DIR%\..\..") do set "INSTALL_DIR=%%~fF"
    set "EXE_PATH=%INSTALL_DIR%\image-viewer.exe"
    set "EXE_FOUND=1"
    goto :found_exe
)

:: Check 3: Three levels up (for green version structure)
if exist "%SCRIPT_DIR%\..\..\..\image-viewer.exe" (
    for %%F in ("%SCRIPT_DIR%\..\..\..") do set "INSTALL_DIR=%%~fF"
    set "EXE_PATH=%INSTALL_DIR%\image-viewer.exe"
    set "EXE_FOUND=1"
    goto :found_exe
)

:: Check 4: Standard LocalAppData location
if exist "%LOCALAPPDATA%\Image-Viewer\image-viewer.exe" (
    set "INSTALL_DIR=%LOCALAPPDATA%\Image-Viewer"
    set "EXE_PATH=%INSTALL_DIR%\image-viewer.exe"
    set "EXE_FOUND=1"
    goto :found_exe
)

:: Check 5: Source build location
if exist "%SCRIPT_DIR%\..\..\target\release\image-viewer.exe" (
    for %%F in ("%SCRIPT_DIR%\..\..\target\release") do set "INSTALL_DIR=%%~fF"
    set "EXE_PATH=%INSTALL_DIR%\image-viewer.exe"
    set "EXE_FOUND=1"
    goto :found_exe
)

:: Not found in any location
if %EXE_FOUND%==0 (
    echo [ERROR] image-viewer.exe not found!
    echo.
    echo Searched locations:
    echo   - %SCRIPT_DIR%\image-viewer.exe
    echo   - %SCRIPT_DIR%\..\..\image-viewer.exe
    echo   - %SCRIPT_DIR%\..\..\..\image-viewer.exe
    echo   - %LOCALAPPDATA%\Image-Viewer\image-viewer.exe
    echo   - %SCRIPT_DIR%\..\..\target\release\image-viewer.exe
    echo.
    echo Please ensure image-viewer.exe exists in one of these locations.
    echo.
    pause
    exit /b 1
)

:found_exe
echo [Portable Mode] Detected green version
echo Installation directory: %INSTALL_DIR%
echo Executable: %EXE_PATH%
echo.

:: Register context menu using HKEY_CURRENT_USER (universal, no admin needed)
echo Registering context menu for Windows %WIN_VER%...
echo Using HKEY_CURRENT_USER (no admin required)
echo.

:: Create temporary registry file with dynamic path
set "TEMP_REG=%TEMP%\image-viewer-install.reg"

(
echo Windows Registry Editor Version 5.00
echo.
echo ; Auto-generated by install.bat
echo ; Universal registry for Windows 7/8/10/11
echo ; Uses HKEY_CURRENT_USER (no admin required)
echo.
) > "%TEMP_REG%"

:: Generate registry entries for all supported image formats
for %%E in (png jpg jpeg gif webp tiff tif bmp ico heic heif avif) do (
    echo [HKEY_CURRENT_USER\Software\Classes\.%%E\shell\OpenWithImageViewer] >> "%TEMP_REG%"
    echo @="Open with Image-Viewer" >> "%TEMP_REG%"
    echo "Icon"="%EXE_PATH:\=\\%" >> "%TEMP_REG%"
    echo. >> "%TEMP_REG%"
    echo [HKEY_CURRENT_USER\Software\Classes\.%%E\shell\OpenWithImageViewer\command] >> "%TEMP_REG%"
    echo @=\"%EXE_PATH:\=\\%\" \"%%1\" >> "%TEMP_REG%"
    echo. >> "%TEMP_REG%"
)

:: Import registry
echo Importing registry entries...
regedit /s "%TEMP_REG%"

if %errorlevel% neq 0 (
    echo.
    echo [ERROR] Failed to import registry!
    echo Please ensure you have write access to HKEY_CURRENT_USER.
    echo (Administrator privileges are NOT required)
    echo.
    del "%TEMP_REG%"
    pause
    exit /b 1
)

:: Clean up
del "%TEMP_REG%"

echo.
echo =========================================
echo Installation completed successfully!
echo =========================================
echo.
echo Image-Viewer path: %EXE_PATH%
echo.
echo You can now right-click on image files to open with Image-Viewer.
echo.
echo Supported formats: PNG, JPG, JPEG, GIF, WebP, TIFF, TIF, BMP, ICO
echo                    HEIC, HEIF, AVIF
echo.
echo Note: This installer uses HKEY_CURRENT_USER and does NOT require
echo       Administrator privileges. It works on Windows 7/8/10/11.
echo.

pause
